development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 2
  port: 5432
  username: postgres
  password: 
production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  database: production
  username: postgres
  password:
